//
//  DummyJDM.swift
//  JDMListDynamic
//
//  Created by Rizky Mashudi on 02/08/21.
//

import Foundation
import UIKit

var heroes: [Jdm] = [
    Jdm(photo: UIImage(named: "evo")!, name: "Lancer Evo VIII", desc: "The Mitsubishi Lancer Evolution, commonly referred to as 'Evo',[1] is a sports sedan based on the Lancer that was manufactured by Japanese manufacturer Mitsubishi Motors from 1992 until 2016. There have been ten official versions to date, and the designation of each model is most commonly a Roman numeral. All use two litre turbocharged inline four-cylinder engines and all-wheel drive systems.[2] The Evolution was originally intended only for Japanese markets, but demand on the grey import market led the Evolution series to be offered through Ralliart dealer networks in the United Kingdom and in various European markets from around 1998. Mitsubishi decided to export the eighth generation Evolution to the United States in 2003 after witnessing the success Subaru had in that market with their long-time direct rival, the Subaru Impreza WRX STi.[3] Japanese-spec[citation needed] versions of all Evos until the release of the Evo IX in 2005 were limited by a gentlemen's agreement to advertise no more than 280 PS (206 kW; 276 hp). However, sources say Mitsubishi had already been producing cars with more power but had been underrating the official power outputs in order to be in compliance with the agreement.[4] Therefore, each subsequent version has unofficially evolved above the advertised power figures, with the Japanese-spec Evolution IX reaching an alleged output of around 321 PS (236 kW; 317 hp). Various versions available in other markets, particularly the UK, have official power outputs up to 446 PS (328 kW; 440 hp). The tenth and final generation of the Lancer Evolution (Evo X) was launched in Japan in 2007, and overseas markets in 2008. The Evo X was produced for almost 10 years until it retired in April 2016."),
    Jdm(photo: UIImage(named: "gtr")!, name: "Nissan GTR R35", desc: "he Nissan GT-R is a high-performance sports car and grand tourer produced by Nissan that was unveiled in 2007.[2][3][4] It is the successor to the Skyline GT-R, a high performance variant of the Nissan Skyline. Although the car is the sixth-generation model to bear the GT-R name, the model is no longer part of the Nissan Skyline model lineup since that name is now reserved for Nissan's luxury-sport vehicles. The GT-R shares the Nissan FM platform with the now separate Nissan Skyline luxury car and the Nissan Z-car sports car."),
    Jdm(photo: UIImage(named: "nsx")!, name: "Acura NSX", desc: "The Honda NSX, marketed in North America as the Acura NSX, is a two-seat, mid-engine coupe[1] sports car manufactured by Honda. The origins of the NSX trace back to 1984, with the HP-X (Honda Pininfarina eXperimental)[2] concept, which was a mid-engine 3.0 L V6 engine rear wheel drive sports car. Honda committed to the project, with the intention of meeting or exceeding the performance of the then V8 engine Ferrari range, while offering reliability and a lower price point. The concept thus evolved and had its name changed to NS-X, which stood for 'New', 'Sportscar', 'eXperimental' ,[3] although the production model was launched as the NSX. Gordon Murray, the designer of the McLaren F1 supercar, stated that he used the NSX as the inspiration for the F1 after test driving many high performance cars and finding the NSX chassis performed the best. Murray stated that the design was 'monumental' to sportscar design. He found that the car could easily have handled more power and attempted to convince Honda to develop a more powerful engine, but they declined. This resulted in Murray developing the F1 with a BMW engine, but he was so fond of the NSX that he bought one for personal use and drove it for 75,000 km. Murray stated that the NSX was 'dear to his heart'"),
    Jdm(photo: UIImage(named: "rx7")!, name: "Mazda rx7", desc: "The Mazda RX-7 is a front/mid-engine, rear-wheel-drive, rotary engine-powered sports car that was manufactured and marketed by Mazda from 1978 to 2002 across three generations, all of which made use of a compact, lightweight Wankel rotary engine. The first generation of the RX-7, SA, was a two-seater 2 door hatchback coupé. It featured a 12A carbureted rotary engine as well as the option for a 13B with electronic fuel injection in later years. The second generation of RX-7, known as the FC, was offered as a 2-seater coupé with a 2+2 option available in some markets, as well as in a convertible bodystyle. This was powered by the 13B rotary engine, offered in naturally aspirated or turbocharged forms. The third generation of the RX-7, known as the FD, was offered a 2+2-seater coupé with a limited run of a 2 seater option. This featured a sequentially turbocharged 13B REW engine. The RX-7 made Car and Driver magazine's Ten Best list five times. More than 800,000 were manufactured over its lifetime."),
    Jdm(photo: UIImage(named: "silviaS15")!, name: "Nissan Silvia S15", desc: "The Nissan Silvia is a long running line of sports coupes. The Silvia S15 is built on the Nissan S Platform. The S15 had fixed headlights, like the S13 and S14 before it.Unlike it's previous versions, the S15 only came in two versions: the standard Spec-S, and the performance Spec-R. Both versions offer an Aero variant, giving the car a large rear wing and side skirts."),
    Jdm(photo: UIImage(named: "supramk4")!, name: "Toyota Supra", desc: "The Toyota Supra (Japanese: トヨタ・スープラ, Toyota Sūpura) is a sports car and grand tourer manufactured by Toyota Motor Corporation beginning in 1978. The name 'supra' is derived from the Latin prefix, meaning 'above', 'to surpass' or 'go beyond'. The initial four generations of the Supra were produced from 1978 to 2002. The fifth generation has been produced since March 2019 and went on sale in May 2019.[4] The styling of the original Supra was derived from the Toyota Celica, but it was both longer and wider.[5] Starting in mid-1986, the A70 Supra became a separate model from the Celica. In turn, Toyota also stopped using the prefix Celica and named the car Supra.[6] Owing to the similarity and past of the Celica's name, it is frequently mistaken for the Supra, and vice versa. The first, second and third generations of the Supra were assembled at the Tahara plant in Tahara, Aichi, while the fourth generation was assembled at the Motomachi plant in Toyota City. The fifth generation of the Supra is assembled alongside the G29 BMW Z4 in Graz, Austria by Magna Steyr. The Supra also traces much of its roots back to the 2000GT owing to an inline-6 layout. The first three generations were offered with a direct descendant to the Crown's and 2000GT's M Along with this name, Toyota also included its own logo for the Supra. It was derived from the original Celica logo, being blue instead of orange. This logo was used until January 1986, when the A70 Supra was introduced. The new logo was similar in size, with orange writing on a red background, but without the dragon design. That logo, in turn, was on Supras until 1991 when Toyota switched to its current oval company logo. (The dragon logo was a Celica logo regardless of what colour it was. It appeared on the first two generations of the Supra because they were officially Toyota Celicas. The dragon logo was used for the Celica line until it too was discontinued.)[citation needed] In 1998, Toyota ceased sales of the fourth generation of the Supra in the United States.[6] Production of the fourth generation of the Supra ended in 2002"),
    Jdm(photo: UIImage(named: "ae86")!, name: "Toyota 86", desc: "The AE86 series of the Toyota Corolla Levin and Toyota Sprinter Trueno are small, front-engine/rear-wheel-drive models within the front-engine/front-wheel-drive fifth generation Corolla (E80) range — marketed by Toyota from 1983 to 1987 in coupé and liftback configurations. Lending themselves to racing, the cars were light, affordable, easily modifiable and combined a five-speed manual transmission, optional limited slip differential, MacPherson strut front suspension, high revving (7800 rpm), twin-cam engine with oil cooler (e.g., in the US), near 50/50 front/rear weight balance, and importantly, a front-engine/rear-drive layout — at a time when this configuration was waning industry-wide. Widely popular for Showroom Stock, Group A, and Group N, Rally and Club racing, the cars' inherent qualities also earned the AE86 an early and enduring international prominence in the motorsport discipline of drifting. The AE86 was featured centrally in the popular, long-running Japanese manga and anime series titled Initial D (1995–2013) — as the main character's drift and tofu delivery car. In 2015, Road & Track called the AE86 'a cult icon, inextricably interwoven with the earliest days of drifting. The AE86 would go on to inspire the Toyota 86 (2012–present),[12] a 2+2 sports car jointly developed by Toyota and Subaru, manufactured by Subaru — and marketed also as the Toyota GT86, Toyota FT86, Scion FR-S and Subaru BRZ."),
    Jdm(photo: UIImage(named: "RWB")!, name: "Porsche RWB", desc: "Nakai later started his own company called RAUH Welt BEGRIFF (RWB) and became known for modifying Porsches, giving them sometimes extreme body conversions.[4] His usual modifications include a new front bumper, rear bumper, side skirts, wheel arches and spoilers. He offers additional options such as new fenders of various width, suspension adjustments and smaller aesthetic additions, like canards and special rivets. The track width of the 'RWB' Porsches is often widened.[5] Nakai's and his company's modifications are said to have reached a 'cult status' and his aesthetics are described as 'singular'"),
    Jdm(photo: UIImage(named: "350z")!, name: "Nissan 350z", desc: "The Nissan 350Z (known as Nissan Fairlady Z (Z33) in Japan) is a two-door, two-seater sports car that was manufactured by Nissan Motor Corporation from 2002 to 2009 and marks the fifth generation of Nissan's Z-car line. The 350Z entered production in 2002 and was sold and marketed as a 2003 model from August 2002. The first year there was only a coupe, as the roadster did not debut until the following year. Initially, the coupe came in Base, Enthusiast, Performance, Touring and Track versions, while the Roadster was limited to Enthusiast and Touring trim levels. The Track trim came with lightweight wheels and Brembo brakes, but its suspension tuning was the same as all other coupes. The Nissan 350Z was succeeded by the 370Z for the 2009 model year.")
]
